services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d stonks_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prefect-server:
    build: ./data_pipeline/
    ports:
      - "4200:4200"
    env_file: .env
    environment:
      - DATABASE_URL
      - NEWS_API_KEY
      - PREFECT_API_URL=http://localhost:4200/api
    volumes:
      - ./data_pipeline:/app
    working_dir: /app
    command: prefect server start --host 0.0.0.0

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@stonks.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS:
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  celery-worker:
      build: ./data_pipeline/
      env_file: .env
      depends_on:
        - rabbitmq
        - postgres
      volumes:
        - ./data_pipeline:/app
      working_dir: /app
      command: celery -A celery_app worker --loglevel=info
      restart: always

  flower:
    build: ./data_pipeline/
    ports:
      - "5555:5555" 
    env_file: .env
    depends_on:
      - celery-worker
      - rabbitmq
    working_dir: /app 
    volumes:
      - ./data_pipeline:/app
    command: celery -A celery_app flower --address=0.0.0.0 --port=5555 --basic_auth=admin:adminpass
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
  rabbitmq_data:
